### ISSUE TITLE
Working with .NET Core

### ISSUE THREAD

**Issue by lovejotd** [microsoft/libyara.NET#22]
I tried to add the package Microsoft.O365.Security.Native.libyara.NET.Core to my .net core project.  I set it to build in x64 only.  But I am getting this error message that say
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Microsoft.O365.Security.Native.libyara.NET.Core 4.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```

When I deploy the resulting project to windows it works okay, but if I try to use it in Linux I am getting some errors.  Am I missing something?  Is this package able to used in Linux?  I tried to look online but couldn't find much help.  Thanks!

**Comment by swannman** [comment]
Hi @lovejotd, thanks for reaching out! This package only works on Windows. On Linux an equivalent technology might be eBPF rather than ETW.
