### ISSUE TITLE
Could not load file or assembly 'libyara.NET, Version=3.5.0.2

### ISSUE THREAD

**Issue by MiddleSiggy** [microsoft/libyara.NET#3]
It looks like the NuGet packages are 64-bit only, and do not work with 32-Bit apps, will this support being compiled as 32-Bit?

{"Could not load file or assembly 'libyara.NET, Version=3.5.0.2, Culture=neutral, PublicKeyToken=176e062142c9110f' or one of its dependencies. The system cannot find the file specified.":"libyara.NET, Version=3.5.0.2, Culture=neutral, PublicKeyToken=176e062142c9110f"}

----------------------
This is from FUSION logging:

LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: libyara.NET, Version=3.5.0.2, Culture=neutral, PublicKeyToken=176e062142c9110f
ERR: Invalid assembly platform or ContentType in file (hr = 0x8007000b).
ERR: Run-from-source setup phase failed with hr = 0x8007000b.

**Comment by kallanreed** [comment]
I'll take a look at what it would take to release an x86 version. It can't be CPU independent because libyara itself is native and has to target x86 or x64.

**Comment by kallanreed** [comment]
The libyara nuget has both 32 and 64 bit native assemblies, it should be easy to release a .Net nuget package that has both. I'll try it tomorrow.

**Comment by kallanreed** [comment]
Nuget doesn't support multiple targets in the same package without some hacky script stuff that runs on package install. I could release a 32 bit package, but it has to be maintained separately.

Is there any reason that you can't target x64 in your app (i.e. are you actually targeting x86 machines)? All you have to do is turn off "Prefer x86" in your project settings and it should compile.

**Comment by MiddleSiggy** [comment]
So my app is an outlook plug in and I am finding that people are still installing the 32-bit version of outlook, even if the system is a 64-bit OS. So I came across this issue just the other day and it is having me rethink my way of solving the problem. I am thinking that maybe I could have the 32-bit app call an instance of the 64-bit dll. Just not sure if that is possible or not.

Joseph Siegmann, CISO
CISSP, CISM, PCI-ISA, MCSE, MCDBA, CCDA, CCNA
IT Security & Compliance.

On Aug 14, 2017, at 4:54 PM, Kyle Reed <notifications@github.com<mailto:notifications@github.com>> wrote:


Nuget doesn't support multiple targets in the same package without some hacky script stuff that runs on package install. I could release a 32 bit package, but it has to be maintained separately.

Is there any reason that you can't target x64 in your app (i.e. are you actually targeting x86 machines)? All you have to do is turn off "Prefer x86" in your project settings and it should compile.

**Comment by kallanreed** [comment]
I added build targets for x86 and pushed a new NuGet package. See b81f556f.
